POST https://api.telegram.org/bot1001583926:AAGmhMtVdEPFCnES9FRsN6xB_GClkwt7LbI/setWebhook
content-type: application/json

{
    "url": "https://dugnadsstrike.azurewebsites.net/api/TelegramMessageReceived",
}



####
https://api.telegram.org/bot1001583926:AAGmhMtVdEPFCnES9FRsN6xB_GClkwt7LbI/getWebhookInfo